# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_displayForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DisplayWindow(object):
    def setupUi(self, DisplayWindow):
        DisplayWindow.setObjectName("DisplayWindow")
        DisplayWindow.resize(747, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DisplayWindow.sizePolicy().hasHeightForWidth())
        DisplayWindow.setSizePolicy(sizePolicy)
        DisplayWindow.setMinimumSize(QtCore.QSize(400, 400))
        DisplayWindow.setMaximumSize(QtCore.QSize(850, 500))
        DisplayWindow.setStyleSheet("#centralwidget{\n"
"    border-image: url(:/resim/kaynakjpg/otostopcunun-galaksi-rehberi-74.jpg);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(DisplayWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnDisplay = QtWidgets.QPushButton(self.centralwidget)
        self.btnDisplay.setGeometry(QtCore.QRect(100, 310, 301, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDisplay.sizePolicy().hasHeightForWidth())
        self.btnDisplay.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Snap ITC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(9)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.btnDisplay.setFont(font)
        self.btnDisplay.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btnDisplay.setAcceptDrops(False)
        self.btnDisplay.setStyleSheet("font: 75 10pt  \"Snap ITC\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(28, 44, 97);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resim/kaynakjpg/Marvin-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDisplay.setIcon(icon)
        self.btnDisplay.setIconSize(QtCore.QSize(100, 100))
        self.btnDisplay.setObjectName("btnDisplay")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(101, 194, 301, 106))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.comboDisParam1 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboDisParam1.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.comboDisParam1.setObjectName("comboDisParam1")
        self.gridLayout.addWidget(self.comboDisParam1, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 0, 1, 1)
        self.comboDisParam2 = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboDisParam2.sizePolicy().hasHeightForWidth())
        self.comboDisParam2.setSizePolicy(sizePolicy)
        self.comboDisParam2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.comboDisParam2.setObjectName("comboDisParam2")
        self.gridLayout.addWidget(self.comboDisParam2, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 2, 0, 1, 1)
        self.comboDisParam3 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboDisParam3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboDisParam3.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.comboDisParam3.setObjectName("comboDisParam3")
        self.gridLayout.addWidget(self.comboDisParam3, 2, 1, 1, 1)
        DisplayWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DisplayWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 747, 26))
        self.menubar.setObjectName("menubar")
        DisplayWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DisplayWindow)
        self.statusbar.setObjectName("statusbar")
        DisplayWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DisplayWindow)
        QtCore.QMetaObject.connectSlotsByName(DisplayWindow)

    def retranslateUi(self, DisplayWindow):
        _translate = QtCore.QCoreApplication.translate
        DisplayWindow.setWindowTitle(_translate("DisplayWindow", "Pivot İşlemler"))
        self.btnDisplay.setToolTip(_translate("DisplayWindow", "CTRL+D"))
        self.btnDisplay.setText(_translate("DisplayWindow", "DISPLAY"))
        self.btnDisplay.setShortcut(_translate("DisplayWindow", "Ctrl+D"))
        self.label_5.setText(_translate("DisplayWindow", "PARAMETRE1"))
        self.label_11.setText(_translate("DisplayWindow", "PARAMETRE2"))
        self.label_17.setText(_translate("DisplayWindow", "PARAMETRE3"))
import kaynak_rc


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     DisplayWindow = QtWidgets.QMainWindow()
#     ui = Ui_DisplayWindow()
#     ui.setupUi(DisplayWindow)
#     DisplayWindow.show()
#     sys.exit(app.exec_())
